[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = ""
authors = ["Taek-Lee00 <dlrlxor548@gmai.com>"]
readme = "README.md"
packages = [{include = "hello_world"}]
repository= "https://github.com/Taek-Lee00/testing"

#main dependency group
[tool.poetry.dependencies]
python = ">=3.10, <3.12"
fastapi = "^0.92.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}


[tool.poetry.group.dev.dependencies]



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
