# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
run-name: Running CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    # Setup virtual environment
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        make install-dev
  
    - name: Lint with flake8
      run: |
        make lint
 
    - name: Test with pytest
      run: |
        make test

    - name: coverage
      run: |
        make coverage
        poetry run coverage xml
        poetry run coverage html

    - name: make badge
      run: |
        make badge

    - name: make docker
      run: |
        make docker

        
